# Generated by Django 3.2 on 2021-04-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210408_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
